name: custom

on: [push]

jobs:
  app:
    name: App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: gradle
      - run: ./gradlew app:assembleRelease
      - uses: actions/upload-artifact@v3
        with:
          name: app-release-unsigned
          path: app/build/outputs/apk/app/release/*.apk
  release:
    name: Sign
    runs-on: ubuntu-latest
    environment: custom
    needs:
      - app
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app-release-unsigned
      - name: Write keystore
        run: echo "$KEYSTORE_BASE64" | base64 --decode > "$KEYSTORE_PATH"
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/keystore.jks
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      - name: Sign APK
        run: $ANDROID_HOME/build-tools/33.0.0/apksigner sign --ks "$KEYSTORE_PATH" --ks-pass env:KEYSTORE_PASSWORD --in *.apk --out app-release.apk
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      - name: Verify APK signature
        run: $ANDROID_HOME/build-tools/33.0.0/apksigner verify --print-certs app-release.apk
      - uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app-release.apk
